name: Generate Consent Management API Docs
on: [push, pull_request]
jobs:
  generate-api-docs:
    name: Generate API Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17
      - name: Install pre-requisites
        run: |
          sudo npm install -g @redocly/cli
          sudo snap install yq
      - name: Generate OpenAPI YAML specs
        run: gradle wrapper build
      - name: Grant permission to run generate-docs.sh script
        run: chmod +x ./scripts/generate-docs.sh
      - name: Generate ReDoc API documentation
        run: ./scripts/generate-docs.sh
